# syntax=docker/dockerfile:1.6
ARG ALPINE_VERSION=3.20
ARG TARGETARCH

FROM alpine:${ALPINE_VERSION}
ARG TARGETARCH
RUN apk add --no-cache ca-certificates
COPY dist/diff-coverage-${TARGETARCH} /usr/local/bin/diff-coverage
ENTRYPOINT ["diff-coverage"]
